# Site settings
title: Lillian's Shop
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: ""
skills: "An 8 year old selling super cool stuff."
meta_author: Jones Jordan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d581b2 #80B3FF
  primary-rgb: "213, 129, 178" #"128,179,255"
  secondary: 656176 #FD6E8A
  secondary-dark: 656176 #A2122F

# Footer settings
footer:
  copyright: Lillian Jones
  location: Location
  social: Source
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Wisconsin

# Credits content
credits: 'My awesome brother made me this website with help from  <a href="http://startbootstrap.com">this theme.</a>.'

# Build settings
markdown: kramdown
permalink: pretty
